[build]
  functions = "functions"
[[redirects]]
  from = "/api/login"
  to = "/.netlify/functions/login"
  status = 200
  force = true
[[redirects]]
  from = "/api/register"
  to = "/.netlify/functions/register"
  status = 200
  force = true
[[redirects]]
  from = "/api/me"
  to = "/.netlify/functions/me"
  status = 200
  force = true
[[redirects]]
  from = "/api/albums"
  to = "/.netlify/functions/albums"
  status = 200
  force = true
[[redirects]]
  from = "/api/albums/:albumId"
  to = "/.netlify/functions/album-detail"
  status = 200
  force = true
[[redirects]]
  from = "/api/albums/:albumId/images"
  to = "/.netlify/functions/album-images"
  status = 200
  force = true
[[redirects]]
  from = "/api/upload"
  to = "/.netlify/functions/upload"
  status = 200
  force = true
[[redirects]]
  from = "/api/images/*"
  to = "/.netlify/functions/images/:imageId"
  status = 200
  force = true